### ISSUE TITLE
Final fixes and changes till last milestone

### ISSUE THREAD

**Issue by Clausioporosis** [Clausioporosis/Stroodle#44]
Final fixes and changes till presentation

**Tasks:**
- [ ] Reverse merge back
- [ ] Highlight day with most votes in participant view
- [ ] Highlight conflicting days in participant and organzier view
- [ ] Show tippy tooltip while selectiong/hovering over weekview
- [ ] render events (excluding background events) horizontally smaller
